name: Zudy
favicon: null
layout_spectrum: 0.26349
typography_spectrum: 0.56165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f18713'
    - '#a29e9d'
    - '#ffffff'
    - '#ff0000'
    - '#ffff00'
  brandStrength: 0.16576246940530837
  lightness: 0.11158855212852359
  saturation: 0.08505520364269614
  rhythmicContrast: 0.19526801630854607
purpose: []
